- name: create the '{{ username }}' user
  user: name={{ username }} append=yes state=present createhome=yes shell=/bin/bash

- name: allow '{{ username }}' to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: set up authorized keys for the {{ username }} user
  authorized_key: user={{ username }} key="{{item}}"
  with_file:
    - "{{ authorized_key }}"