- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory
  become: yes
  become_user: kubernetes
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kubernetes/.kube/config
    remote_src: yes
    owner: kubernetes

- name: copy kube-flannel.yml to remote
  copy:
    src: kube-flannel.yml
    dest: /home/kubernetes/kube-flannel.yml
    owner: kubernetes

- name: install Pod network
  become: yes
  become_user: kubernetes
  shell: kubectl apply -f /home/kubernetes/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

- name: install kubectl
  apt:
    name: kubectl=1.14.0-00
    state: present
    force: yes