---
# This playbook deploys the entire Kubernetes cluster

- name: keyscan remote hosts to ~/.ssh/known_hosts
  hosts: all
  gather_facts: no
  serial: 1
  roles:
    - keyscan-host

- name: apply kubernetes master configuration to master nodes
  hosts: kubernetes-master
  remote_user: root

  roles:
  - kubernetes-master